name: buddy
# This build can be kicked off manually from any branch and is the same as what the PR build will do.
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
          
    - name: Restore Packages
      run: nuget restore SyncKusto.sln

    - name: Build Solution
      run: msbuild.exe SyncKusto.sln /p:Configuration=Release  
      
