name: pullrequest
# Do the same build as the official build but don't publish artifacts.

on:
  # Trigger on pull requests or can be run manually on branches too
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@ede762b26a2de8d110bb5a3db4d7e0e080c0e917 # v1.3.3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1 # v1.0.5
          
    - name: Restore Packages
      run: nuget restore SyncKusto.sln

    - name: Build Solution
      run: msbuild.exe SyncKusto.sln /p:Configuration=Release  
      
