name: pullrequest
# Do the same build as the official build but don't publish artifacts.

on:
  # Trigger on pull requests or can be run manually on branches too
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
          
    - name: Restore Packages
      run: nuget restore SyncKusto.sln

    - name: Build Solution
      run: msbuild.exe SyncKusto.sln /p:Configuration=Release  
      
